import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./../globals.css";
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: 'Food Panda',
    template: '%s | Food Panda'
  },
  description: "Generated by create next app",
};


export default function RootLayout({ children}) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className="min-h-screen flex flex-col justify-between"
      >
        <Navbar/>
        <main className="flex-grow">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
